### ISSUE TITLE
pop-build - issue on centos6

### ISSUE THREAD

**Issue by ggaddy** [saltstack/pop-build#2]
hey! I installed pop-build from pypi and the python executable it installs under /usr/bin/pop-build isnt working

```
# install pop-build python3 package
[root@e435611070e9 salt-bin]# python3 -m pip install pop-build

# test pop-build
[root@e435611070e9 salt-bin]# /usr/local/bin/pop-build
Traceback (most recent call last):
  File "/usr/local/bin/pop-build", line 5, in <module>
    from popbuild.scripts import start
ModuleNotFoundError: No module named 'popbuild'
```

I do see a file scripts is under /usr/local/lib/python3.6/site-packages/pop/scripts.py but this doesnt have a start function defined

```
[root@e435611070e9 salt-bin]# more /usr/local/lib/python3.6/site-packages/pop/scripts.py  | grep "^def"
def pop_seed():
```

**Comment by apex-omontgomery** [comment]
I'm encountering same issue on windows 10 with python 3.7. 
```posh
(venv) C:\Users\wimo7\Desktop\salt-bin [master ≡]> pop-build -n salt
Traceback (most recent call last):
  File "c:\users\wimo7\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\wimo7\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\wimo7\AppData\Local\Programs\Python\Python37-32\Scripts\pop-build.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'popbuild'
```

```posh
(venv) C:\Users\wimo7\Desktop\salt-bin [master ≡]> pip freeze | grep pop
pop==7.6
pop-build==1
```

**Comment by apex-omontgomery** [comment]
Working through this trying to get it working. 
```
git clone https://github.com/saltstack/pop-build.git pop-build
rename to `popbuild` https://github.com/saltstack/pop-build/blob/42406b34eb39965ff70dbc3a99f2bd0a299f3b61/setup.py#L10
pip install -e . 
```

```
Python 3.8.1 (default, Jan 22 2020, 10:22:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import popbuild
>>> print(dir(popbuild))
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```


Not a very good error for missing CLI arguments argument?

```
wmontgomery@build_vm:~$ pop-build
Traceback (most recent call last):
  File "/home/wmontgomery/.pyenv/versions/3.8.1/bin/pop-build", line 11, in <module>
    load_entry_point('popbuild', 'console_scripts', 'pop-build')()
  File "/home/wmontgomery/pop-build/popbuild/scripts.py", line 7, in start
    hub.popbuild.init.cli()
  File "/home/wmontgomery/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pop/contract.py", line 131, in __call__
    return self.func(*args, **kwargs)
  File "/home/wmontgomery/pop-build/popbuild/popbuild/init.py", line 18, in cli
    hub.popbuild.init.builder(
  File "/home/wmontgomery/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pop/contract.py", line 131, in __call__
    return self.func(*args, **kwargs)
  File "/home/wmontgomery/pop-build/popbuild/popbuild/init.py", line 107, in builder
    bname = hub.popbuild.init.new(name, requirements, sys_site, exclude, directory, dev_pyinst, build, onedir, pyenv)
  File "/home/wmontgomery/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pop/contract.py", line 131, in __call__
    return self.func(*args, **kwargs)
  File "/home/wmontgomery/pop-build/popbuild/popbuild/init.py", line 50, in new
    s_path = os.path.join(venv_dir, 'bin', name)
  File "/home/wmontgomery/.pyenv/versions/3.8.1/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/wmontgomery/.pyenv/versions/3.8.1/lib/python3.8/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```


pop-build -n salt and both pop -h attempt to do something

```wmontgomery@build_vm:~$ pop-build -h
usage: pop-build [-h] [--build BUILD] [-c CONFIG] [--dev-pyinstaller] [-D DIRECTORY] [-e EXCLUDE] [--log-datefmt LOG_DATEFMT] [--log-file LOG_FILE]
                 [--log-fmt-console LOG_FMT_CONSOLE] [--log-fmt-logfile LOG_FMT_LOGFILE] [--log-level LOG_LEVEL] [--log-plugin LOG_PLUGIN] [-n NAME] [--onedir]
                 [--pyenv PYENV] [-r REQUIREMENTS] [-S]

wmontgomery@build_vm:~/salt-bin$ pop-build -n salt
Collecting distro
  Using cached https://files.pythonhosted.org/packages/ea/35/82f79b92fa4d937146c660a6482cee4f3dfa1f97ff3d2a6f3ecba33e712e/distro-1.4.0-py2.py3-none-any.whl
Installing collected packages: distro
Successfully installed distro-1.4.0
WARNING: You are using pip version 19.2.3, however version 20.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Ignoring tornado: markers 'python_version < "3"' don't match your environment
Ignoring futures: markers 'python_version < "3.0"' don't match your environment
Collecting salt (from -r /home/wmontgomery/salt-bin/__build_requirements.txt (line 2))
```


When the above is working and I try and use it for salt-bin I run into the following errors- `pop-build -n salt`

1. requirements.txt doesn't want to install 
`git+https://github.com/Ch3LL/salt.git@v2019.2.2-1`/tmp is out of space (/tmp has 363MB free) correction: When I replace with `salt`
1. distro is not found 
salt expects `distro` but isn't listed as a dependency,
correction: pip install distro
1. missing python3.8 library with pyenv
`OSError: Python library not found: libpython3.8.so.1.0, libpython3.8m.so.1.0, libpython3.8m.so, libpython3.8mu.so.1.0`
correction:
OSError: Python library not found: libpython3.8.so.1.0, libpython3.8m.so.1.0, libpython3.8m.so, libpython3.8mu.so.1.0
`PYTHON_CONFIGURE_OPTS='--enable-shared' LDFLAGS=`"-Wl,-rpath=$HOME/.pyenv/versions/3.8.1/lib" pyenv install 3.8.1`
1. pyInstaller error because I forgot python3.8 is not supported. 
```
Traceback (most recent call last):
  File "/home/wmontgomery/.pyenv/versions/3.8.1/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wmontgomery/.pyenv/versions/3.8.1/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/tmprich5978/lib/python3.8/site-packages/PyInstaller/__main__.py", line 118, in <module>
    run()
  File "/tmp/tmprich5978/lib/python3.8/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/tmp/tmprich5978/lib/python3.8/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/tmp/tmprich5978/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/tmp/tmprich5978/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "./salt.spec", line 18, in <module>
    pyz = PYZ(a.pure, a.zipped_data,
  File "/tmp/tmprich5978/lib/python3.8/site-packages/PyInstaller/building/api.py", line 98, in __init__
    self.__postinit__()
  File "/tmp/tmprich5978/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/tmp/tmprich5978/lib/python3.8/site-packages/PyInstaller/building/api.py", line 128, in assemble
    self.code_dict = {
  File "/tmp/tmprich5978/lib/python3.8/site-packages/PyInstaller/building/api.py", line 129, in <dictcomp>
    key: strip_paths_in_code(code)
  File "/tmp/tmprich5978/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 652, in strip_paths_in_code
    consts = tuple(
  File "/tmp/tmprich5978/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 653, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "/tmp/tmprich5978/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 660, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: an integer is required (got type bytes)
Executable created in dist/salt
```
Try this command before giving up for now and going to 3.7
`pop-build -n salt --pyenv 3.8.1` (this appears to trigger a pyenv install 3.8.1) 
which outputs the same pyinstaller error.


It appears there's some undeclared dependencies on the initial contributors that is allowing this to work (example, you renamed the popbuild module and the old one probably persisted). I'd highly recommend using containers  or at least fresh build/ development environments (instead of pyenv) or other things that kinda sorta make your build environment fresh.

**Comment by thatch45** [comment]
Oh! I know this one, gimme a second.

As for the python 3.8 thing, that is in pyinstaller, it does not support 3.8 yet, you need to pass --dev-pyinst to run the development version of pyinstaller, and hope, but for now I would target 3.7

**Comment by thatch45** [comment]
@wimo7083 can you file the rest of this issue in salt-bin? looks like I forgot to add the distro package to the requirements.txt

**Comment by thatch45** [comment]
@wimo7083 I have not gotten this to run and build at all on Windows yet, any help is appreciated

**Comment by thatch45** [comment]
Ok, I pushed a new release with the name and path fixes

**Comment by apex-omontgomery** [comment]
Awesome thank you, I'll give this a shot and file an issue in salt-bin with any other problems/ fixes.

I have a windows machine that I can use to help with, but I'm pretty lacking of windows sysadmin knowledge that would be required to do much. I'm pretty good at googling though.

**Comment by apex-omontgomery** [comment]
Oddly enough things work fine with pyenv 3.7.6 and the corrected release. Distro wasn't needed.
